# Generated by Django 3.2.5 on 2022-03-02 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_alter_weather_data_record_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_data',
            name='record_entry_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
